version: '3.4'
services:
  jenkins:
        image: jenkins/jenkins
        container_name: jenkins
        restart: always
        ports:
                - 8080:8080
  db:
        image: postgres
        restart: always
        container_name: db
        ports:
                - 5432:5432
        environment:
                POSTGRES_PASSWORD: "1234"
        volumes:
                - /home/centos/docker-compose/PostgreSQL:/var/lib/postgresql/data
  pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin 
        restart: always
        environment:
                PGADMIN_DEFAULT_EMAIL: "adailton.silva10@live.com"
                PGADMIN_DEFAULT_PASSWORD: "1234"
        ports:
                - 80:80
        depends_on:
        - db
