version: '3.4'
services:
  jenkins:
        image: jenkinsci/blueocean
        container_name: jenkins
        restart: always
        user: root
        ports:
                - 8080:8080
        volumes:
                - ./jenkins-data:/var/jenkins_home
                - /var/run/docker.sock:/var/run/docker.sock
  db:
        image: postgres
        restart: always
        container_name: db
        ports:
                - 5432:5432
        environment:
                POSTGRES_PASSWORD: "senha"
        volumes:
                - /home/centos/docker-compose/PostgreSQL:/var/lib/postgresql/data
  pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin 
        restart: always
        environment:
                PGADMIN_DEFAULT_EMAIL: "email"
                PGADMIN_DEFAULT_PASSWORD: "senha"
        ports:
                - 80:80
        depends_on:
        - db
